# Generated by Django 4.1.1 on 2022-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ejercicio_12_1_Directores_Cine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='gender_of_movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='summary of the movie', max_length=550),
        ),
    ]
