# Generated by Django 4.1.1 on 2022-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ejercicio_12_1_Directores_Cine', '0003_genre_remove_movie_gender_of_movie_delete_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_of_movie',
        ),
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(limit_choices_to=15, to='App_Ejercicio_12_1_Directores_Cine.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_of_movie',
            field=models.ManyToManyField(limit_choices_to=5, to='App_Ejercicio_12_1_Directores_Cine.genre'),
        ),
    ]
